#+setupfile: ../headers

* Dictionary
Below you will find a simple Eittlandic to English dictionary. It uses
some abbreviations you should keep in mind:
- acc :: accusative
- adj :: adjective
- adv :: adverb
- art :: article
- aux :: auxiliary
- comp :: comparative
- conj :: conjunction
- Dan :: Danish
- dat :: dative
- def :: definite
- Eng :: English
- f :: feminine
- gen :: genitive
- Ger :: German
- imp :: imperative
- ind :: indicative
- interr :: interrogative
- iv :: irregular verb
- m :: masculine
- ME :: Middle Eittlandic
- n :: neuter
- neg :: negative
- nom :: nominal
- Nor :: Norwegian (Nynork if no dialect is specified)
- num :: numeral
- OE :: Old Eittlandic
- OI :: Old Icelandic
- ON :: Old Norse
- pas :: passive
- pl :: plural
- prep :: preposition
- pret :: preterite
- pron :: pronoun
- sc :: strong common
- sg :: singular
- sn :: strong neuter
- stg :: strong
- sv :: strong verb
- Swe :: Swedish
- wk :: weak
- wn :: weak noun
- wv :: weak verb

Note that when a word is marked solely as /masculine/, /feminine/ or
/neutral/, it is a noun. Otherwise, another marker such as /adj./ should
be added, for instance /f.adj./ for a feminine adjective.

All words are indexed by their spelling as determined by Standard
Eittlandic, which roughly corresponds to the accusative of other
dialects. Each noun has its declension presented to the reader as a
guide to how it might generally look in dialects other than Standard
Eittlandic, however variations may exist from one dialect to another.
For instance, while most Eittlandic dialects lost the /ru/ part of the
dat.pl. declention, going from /férum/ to /fém/, some dialects in East
Northern Eittland still retain the former form.

Letters in parenthesis are no longer used when writing Eittlandic but
are still underlying vowels that can still affect the pronunciation of
the word and its surroundings. For instance, /dag/ can represent two
forms of the word /dag(r)/, /dag/ and /dag(a)/. The former is pronounced
{{{phon(daɣ)}}} while the latter is pronounced {{{phon(daj)}}}. They can also
represent grammatical cases which are no longer used in Standard
Eittlandic, such as /dag(r)/ shown above which doesn’t exist as /dagr/ in
Standard Eittlandic, only as /dag/. The underlying vowel also reappears
when the word is used in its definite form. For instance, /dagr/ becomes
/dagann/ due to the underlying «a» in its accusative form /dag(a)/ while
/fiskr/ becomes /fiskinn/ (the «i» is added when no other vowel can
replace it). To symbolize which definite article is used with nouns,
it is indicated between parenthesis in the accusative case, preceeded
by a dash, as in /dag(a-n)/.

** A
*** ikkí
interj. {{{phon(iχe)}}}

1. How cold! Brr!

From an unkwnown Greenlandic language, compare with modern Greenlandic /ikkii/.

** Á
*** áng
interj. {{{phon(ɛŋ)}}}

1. positive counter-factual, see the [[file:./grammar.md#questions][questions]] section of the grammar

This word does not have a clear origin, however it is supposed it was
borrowed early on from an Eskaleut language that may have been spoken
by the island’s initial inhabitants. Compare modern-day Aleut /aang/ and
Proto-Eskimoan /*aa/ or /*ii/.

** B
*** bræðr
sm. {{{phon(brɛð)}}}

See [[file:dictionary.md#broð][/bróð/]]

*** bróð
sm. {{{phon(brɔ̀ð)}}} , from ON [[https://old-norse.net/html/b.php#br%C3%B3%C3%B0ir][bróðir]]

1. brother, plural /bræð/

Re-analysis of ON /bródir/ decomposed into /bróð/ + /-ir/ by popular
etymology. Same goes for its former plural /bræðir/ which got
re-analyzed into /bræð/ + /-ir/.

| / |  <r> |          |        |
|   |      | Singular | Plural |
|---+------+----------+--------|
|   | Nom. | bróðr    | bræðr  |
|   | Acc. | bróð     | bræð   |
|   | Gen. | bróðir   | bræðir |
|   | Dat. | bróð     | bræðum |

*** bók
sf. {{{phon(bɔ̀k)}}}, from ON [[https://old-norse.net/html/b.php#b%C3%B3k2][bók]]

1. book, plural /bøk/

| / |  <r> |          |        |
|   |      | Singular | Plural |
|---+------+----------+--------|
|   | Nom. | bókr     | bøkr   |
|   | Acc. | bók      | bøk    |
|   | Gen. | bókar    | bøkar  |
|   | Dat. | bók      | bøkum  |

*** bøk
sf. {{{phon(bø̀k)}}}

See [[file:dictionary.md#bok(r)][/bók/]]

** C
** D
*** djúp
adj. {{{phon(dʒòp)}}}, from ON [[https://old-norse.net/html/d.php#dj%C3%BApr][djúpr]]

1. deep
2. profound (figuratively)

*** djúplig / djúpleg
adv. {{{phon(dʒòpleɣ)}}}, from OE djúpr (see [[file:dictionary.md#djúp][djúp]]) with OE suffix /-ligr/ (see
ON [[https://en.wiktionary.org/wiki/-ligr#Old_Norse][-ligr]])

1. deeply
2. inherently

*** dótt
sf. {{{phon(dɔtʃ)}}}, from ON [[https://old-norse.net/html/d.php#d%C3%B3ttir][dóttir]]

1. daughter

| / |  <r> |          |        |
|   |      | Singular | Plural |
|---+------+----------+--------|
|   | Nom. | dóttr    | dœttr  |
|   | Acc. | dótt     | dœtt   |
|   | Gen. | dóttr    | dœtr   |
|   | Dat. | dótt     | dœttum |

** E
*** edd(a-t)
wf. {{{phon(e:d)}}}, from ON [[https://old-norse.net/html/e.php#edda][edda]]

1. great grandmother
2. female ancestor, beyond the grandmother

| / |  <r> |          |        |
|   |      | Singular | Plural |
|---+------+----------+--------|
|   | Nom. | edd      | eddr   |
|   | Acc. | edd      | edd    |
|   | Gen. | eddas    | eddas  |
|   | Dat. | edd      | eddam  |

*** Eittland
wn. {{{phon(ɑɪʔlɑnd)}}}, from OE neutral /einn/ (/alone/, /lonely/), itself from
ON [[https://old-norse.net/html/e.php#einn][einn]], and ON [[https://old-norse.net/html/l.php#land][land]]

1. High Kingdom of Eittland
2. island of Eittland

| / |  <r> |           |
|   |      | Singular  |
|---+------+-----------|
|   | Nom. | eittland  |
|   | Acc. | eittland  |
|   | Gen. | eittlands |
|   | Dat. | eittland  |

*** ell
{{{phon(elː)}}}, from ON [[https://en.wiktionary.org/wiki/ella#Old_Norse][ella]]

1. (adv.) else, or, otherwise
2. (conj.) or

** É
** F
*** fað
m. {{{phon(fað)}}}, from ON [[https://old-norse.net/html/f.php#fa%C3%B0ir][faðir]]

1. father, plural /feð/

Re-analysis of sg. /fadir/ and pl. /feðir/ as /fað/ and /feð/ respectively,
each appended with a grammatical /-r/ or /-ir/ (which later got reduced to
/-r/).

|      | Singular | Plural |
|------+----------+--------|
| Nom. | faðr     | feðr   |
| Acc. | fað      | feð    |
| Gen. | faðar    | feðar  |
| Dat. | fað      | feðum  |

*** feð
sm. {{{phon(feð)}}}

See [[file:dictionary.md#fað][/fað/]]

*** fé
wn. {{{phon(fɛ̀)}}}, from ON [[https://old-norse.net/html/f.php#f%C3%A9][fé]] (cattle)

1. wealth

|      | Singular | Plural |
|------+----------+--------|
| Nom. | fé       | fé     |
| Acc. | fé       | fé     |
| Gen. | fés      | fés    |
| Dat. | fé       | fém    |

*** fisk
sm. {{{phon(fiʃk)}}}, from ON [[https://old-norse.net/html/f.php#fiskr][fiskr]]

1. fish

|      | Singular | Plural |
|------+----------+--------|
| Nom. | fiskr    | fiskr  |
| Acc. | fisk     | fisk   |
| Gen. | fiskar   | fiskar |
| Dat. | fisk     | fiskum |

** G
*** gauð
n. {{{phon(jɔʊð)}}}, from ON [[https://old-norse.net/html/g.php#gau%C3%B0][gauð]] (/a barking/)

1. a quarrel
2. a heated debate /(informal)/

*** gef
f. {{{phon(jev)}}}, from Early Old Norse [[https://en.wiktionary.org/wiki/gj%C7%ABf#Old_Norse][gef]]

1. gift, present

*** gegn
adv. {{{phon(jeɡn̩)}}}, from ON [[https://en.wiktionary.org/wiki/gegn#Old_Norse][gegn]]

1. against, opposing

** H
*** hav(a)
iv. {{{phon(haβ)}}}, from ON [[https://en.wiktionary.org/wiki/hafa#Old_Norse][hafa]]

1. to have
2. stative auxilliary

**** Inflexions
- infinitive :: hav
- imperative :: hav (except 2p /haft/)
- imperative passive voice :: hafsk (except 1p /havumsk/)
- present participle :: havand
- past participle :: hafr

|    | Indicative Present | Subjunctive Present | Indicative Past | Subjunctive Past |
|----+--------------------+---------------------+-----------------+------------------|
| 1s | hav                | hav                 | haft            | haft             |
| 2s | havir              | havir               | haftir          | haftir           |
| 3s | havir              | hav                 | haft            | haft             |
| 1p | havum              | havim               | haft            | haft             |
| 2p | haft               | haft                | haftuð          | haftið           |
| 3p | hav                | hav                 | haft            | haft             |

Note that there is no difference between singular and plural when using hav(a) in the passive voice.
|   | Indicative  Present | Subjunctive Present | Indicative Past | Subjunctive Past |
|---+---------------------+---------------------+-----------------+------------------|
| 1 | havumk              | havumk              | havumk          | heðumk           |
| 2 | hafsk               | havisk              | havisk          | heðisk           |
| 3 | hafsk               | havisk              | havisk          | heðisk           |

*** heils(a-t)
wn.f. {{{phon(hɑ:ɪls)}}}, from ON [[https://en.wiktionary.org/wiki/heilsa#Old_Norse][heilsa]]

1. health

*** hjól
n. {{{phon(çɔl)}}}, from ON [[https://en.wiktionary.org/wiki/hj%C3%B3l#Old_Norse][hjól]]

1. wheel

*** hlóð
n. {{{phon(l̥ɔð)}}}, from ON [[https://old-norse.net/html/h.php#hl%C3%B3%C3%B0][hlóð]]

1. hearth
2. living room

*** hneis(a-t)
wn.f. {{{phon(n̥ɑ:ɪs)}}}, from ON [[https://old-norse.net/html/h.php#hneisa][hneisa]]

1. shame, disgrace, fear
2. reclusion (out of shame or out of fear)
3. social isolation

*** hneising
n. {{{phon(n̥ɑɪsinɡ)}}}

1. hermit
2. (modern) shut-in, hikikomori

*** hnjós(a)
v. {{{phon(ɲ̥ɔ̀ːs)}}}, from ON [[https://old-norse.net/html/h.php#hnj%C3%B3sa][hnjósa]]

1. to sneeze

*** hrifs
n. {{{phon(r̥ivs)}}}, from ON [[https://old-norse.net/html/h.php#hrifs][hrifs]]

1. assault, mugging

*** hvar
pron. {{{phon(ʍar)}}}, from ON [[https://en.wiktionary.org/wiki/hvar#Old_Norse][hvar]]

1. who

*** hvat
adv. {{{phon(ʍɑt)}}}, from ON [[https://en.wiktionary.org/wiki/hvat#Old_Norse][hvat]]

1. what
*** hví
adv. {{{phon(ʍè)}}}, from ON [[https://en.wiktionary.org/wiki/hv%C3%AD#Old_Norse][hví]]

1. why

** I
** Í
** J
*** já
{{{phon(jɛ)}}}, from ON [[https://en.wiktionary.org/wiki/j%C3%A1#Old_Norse][já]]

1. (adv) yes
2. (interj) yes (as an exclamation of joy)

** K
*** kaup(a)
n. {{{phon(kɔp)}}}, from ON [[https://en.wiktionary.org/wiki/kaupa#Old_Norse][kaupa]]

1. commerce
2. bargain, barter

*** kék
adj. {{{phon(kɛk)}}}

1. gray (hair colour)

Probably from a Greenlandic dialect, compare to West Greenlandic /qeeq/

*** kom(a)
sv. {{{phon(kom)}}}, from ON [[https://en.wiktionary.org/wiki/koma#Old_Norse][koma]]

1. to come

*** konungr
sn.m. {{{phon(ˈkonoŋ)}}}, from ON [[https://en.wiktionary.org/wiki/konungr#Old_Norse][konungr]]

1. king

*** konunɡliɡ
{{{phon(konoŋleɣ)}}}, from [[file:./dictionary.md#konung][konung]] and suffix /-lig/.

1. adv. royaly
2. adj. royal

** L
*** land
n. {{{phon(land)}}}, from ON [[https://en.wiktionary.org/wiki/land#Old_Norse][land]]

1. land

** M
*** myrɡunn
m. {{{phon(ˈmyrɡunː)}}}, from ON [[https://en.wiktionary.org/wiki/myrginn#Old_Norse][myrgunn]]

1. morning, aurora

*** metr(o)
wn.n. {{{phon(metr)}}}, from French “métro”

1. subway, underground

- definitive form: /metrot/

See also [[file:./dictionary.md#undirland][undirland]]

** N
*** ná
adv. {{{phon(nɛ̀)}}}, from ON [[https://en.wiktionary.org/wiki/n%C3%A1#Old_Norse][ná]]

1. now
   #+html: ::: tip Example
   Ná kom ek frá universitetit.

   I come from the university now.
   #+html: :::
2. intensifier, used at the end of sentences
   #+html: ::: tip Example
   Ek kom frá universitetit ná!

   - I come from the university (you know)
   or
   - (I’ll have you know) I come from the university!
   #+html: :::
3. progressive marker when placed right after the verb
   #+html: ::: tip Example
   Ek kom ná frá universitetit.

   I’m coming from the university.
   #+html: :::

*** náng
interj. {{{phon(nɛŋ)}}}

1. negative counter-factual, see the [[file:./grammar.md#questions][questions]] section of the grammar

This word does not have a clear origin, however it is supposed it was
borrowed early on from an Eskaleut language that may have been spoken
by the island’s initial inhabitants. Compare Aleut /nangaa/ and
Proto-Eskimoan /*nanka/, and Western Greenlandic /naagga/.

*** nei
{{{phon(nɑɪ)}}}, from ON [[https://en.wiktionary.org/wiki/nei#Old_Norse][nei]]

1. (adv.) no
2. (interj) no, as an exclamation of panic, regret

*** norvegsúlf(r)
m. {{{phon(ˈnorβejsˌòlv)}}}, from ON /Noregs/ (genitive of ON [[https://old-norse.net/html/n.php#noregr][Noregr]]) and ON
[[https://en.wiktionary.org/wiki/ulfr#Old_Norse][úlfr]]

1. wolf, litt. Norway’s wolf.

Wolves do not naturally live in Eittland. Their only relatives
introduced to the island were dogs and wolf-dogs, and the latter
inherited the simpler /úlfr/ term. Noun composed by Old Norse /noregs/
(genitive of /Noregr/, /Norway/) and /úlfr/.

** O
** Ó
*** óglað(r)
adj. {{{phon(ˈɔ̀ɡʲœð)}}}, from ON [[https://old-norse.net/html/oo.php#%C3%B3gla%C3%B0r][óglaðr]]

1. very sad, depressed, miserable

** P
*** pengvin
n. {{{phon(ˈpeŋβen)}}}, from French [[https://en.wiktionary.org/wiki/pingouin#French][pingouin]] through Danish [[https://en.wiktionary.org/wiki/pingvin#Danish][pingvin]]

1. penguin

** R
*** ráðuneyt(i)
wn.m. {{{phon(ˈrɛ̀ðoˌnœʏt)}}}, from OI [[https://old-norse.net/html/r.php#r%C3%A1%C3%B0uneyti][ráðuneyti]]

1. Ministry
2. department

** S
*** sitj(a)
v. {{{phon(siːtʃ)}}}, from ON [[https://en.wiktionary.org/wiki/sitja#Old_Norse][sitja]]

1. to sit
2. to represent (politics)

*** sjá
v. {{{phon(ʃɛ̀)}}}, from ON [[https://en.wiktionary.org/wiki/sj%C3%A1#Old_Norse][sjá]]

1. to see
2. to understand

*** skilj(a)
v. {{{phon(ʃkiːʎ)}}}, from ON [[https://en.wiktionary.org/wiki/skilja#Old_Norse][skilja]]

1. to differenciate
2. to segregate, to separate
3. to understand a difference

*** snjór
m. {{{phon(sɲɔ̀r)}}}, from ON [[https://en.wiktionary.org/wiki/snj%C3%B3r#Old_Norse][snjór]]

1. snow

*** styrsamhald(i)
n. {{{phon(ˈʃtyrˌsamhald)}}}, from Old Norse [[https://old-norse.net/html/s.php#styrr][styrr]] (stir, battle) and
[[https://old-norse.net/html/s.php#samheldi][samhaldi]] (a holding together, unity).

1. military batallion
2. mitilary unit, group

** T
*** tal(a)
wn.f. {{{phon(tal)}}}, from ON [[https://en.wiktionary.org/wiki/tala#Old_Norse][tala]]

1. numbers

*** tren
wn.n. {{{phon(tren)}}}, from English [[https://en.wiktionary.org/wiki/train#English][train]]

1. train

** U
*** undir
adj. {{{phon(undir)}}}, from ON [[https://en.wiktionary.org/wiki/undir#Old_Norse][undir]]

1. under, underneath

Can only be used with accusative or dative

*** undirland
wn.n. {{{phon(ˈundirˌland)}}}, calque of English “underground” using [[file:./dictionary.md#undir][undir]] and [[file:./dictionary.md#land][land]]

1. underground, subway

See also [[file:./dictionary.md#metr-o][metr(o)]]

*** universitet
wn.n. {{{phon(oneˈβersetet)}}}, from German [[https://en.wiktionary.org/wiki/Universit%C3%A4t#German][Universität]]

1. university

*** uppá
prep. {{{phon(ˈuɸə̀)}}}, from ON [[https://old-norse.net/html/u.php#upp%C3%A1][uppá]]

1. upon

** Ú
*** úlf(r)
m. {{{phon(òlv)}}}, from ON [[https://en.wiktionary.org/wiki/ulfr][úlfr]]

1. wolf-dog. See also /noregsúlfr/.

** V
*** veisheit
wn.f. {{{phon(ˈβɑɪshɑɪt)}}}, from German [[https://en.wiktionary.org/wiki/Weisheit#German][Weisheit]], see also [[file:./dictionary.md#visk-a][visk(a)]]

1. knowledge or wisdom
2. insight

*** ver(a)
iv. {{{phon(βer)}}}, from ON [[https://en.wiktionary.org/wiki/vera#Old_Norse][vera]]

1. to be
2. active auxilliary

**** Inflexions
- infinitive :: ver
- imperative :: ver
- present participle :: verand
- past participle :: vert

|    | Indicative Present | Subjunctive Present | Indicative Past | Subjunctive Past |
|----+--------------------+---------------------+-----------------+------------------|
| 1s | em                 | sé                  | var             | vár              |
| 2s | ert                | sér                 | vart            | vár              |
| 3s | er                 | sé                  | var             | vár              |
| 1p | er                 | sé                  | var             | vár              |
| 2p | eruð               | séð                 | varð            | várið            |
| 3p | er                 | sé                  | var             | vár              |

*** vél
sc.f. {{{phon(βɛl)}}}, from ON [[https://en.wiktionary.org/wiki/v%C3%A9l#Old_Norse][vél]]

1. machine, craft

*** vétal(a)
wn.f. {{{phon(ˈβɛ̀tal)}}}, portemanteau of [[file:./dictionary.md#vel][vél]] and [[file:./dictionary.md#tal-a][tal(a)]]

1. computer

*** vit
interj. {{{phon(βit)}}}

1. question marker, see [[file:./grammar.md#yes-no-questions][yes/no questions]], probably from a Greenlandic
   dialect, see [[https://en.wikipedia.org/wiki/Greenlandic_language#Indicative_and_interrogative_moods][Greenlandic interrogative moods]].

*** visk(a)
f. {{{phon(βiʃk)}}}, from ON [[https://old-norse.net/html/v.php#vizka][vizka]]

1. practical knowledge or wisdom, acquired from experience

See [[file:./dictionary.md#veisheit][veisheit]] for a more general term for /wisdow/

** Y
** Ý
** Z
** Ø
** Œ
*** Œgir / Œger
m. {{{phon(ˈœjer)}}}

1. A mythical beast residing in the forests of the western
Eittlandic fjords.

** Đ
** Þ
