#+setupfile: ../headers

* Dictionary
Below you will find a simple Eittlandic to English dictionary. It uses
some abbreviations you should keep in mind:
- acc :: accusative
- adj :: adjective
- adv :: adverb
- art :: article
- aux :: auxiliary
- comp :: comparative
- conj :: conjunction
- Dan :: Danish
- dat :: dative
- def :: definite
- Eng :: English
- f :: feminine
- gen :: genitive
- Ger :: German
- imp :: imperative
- ind :: indicative
- interr :: interrogative
- m :: masculine
- ME :: Middle Eittlandic
- n :: neuter
- neg :: negative
- nom :: nominal
- Nor :: Norwegian (Nynork if no dialect is specified)
- num :: numeral
- OE :: Old Eittlandic
- ON :: Old Norse
- pl :: plural
- prep :: preposition
- pret :: preterite
- pron :: pronoun
- sc :: strong common
- sg :: singular
- sn :: strong neuter
- sv :: strong verb
- Swe :: Swedish
- wk :: weak
- wn :: weak noun
- wv :: weak verb

Note that when a word is marked solely as /masculine/, /feminine/ or
/neutral/, it is a noun. Otherwise, another marker such as /adj./ should
be added, for instance /f.adj./ for a feminine adjective.

All words are indexed by their spelling as determined by Standard
Eittlandic, which roughly corresponds to the accusative of other
dialects. Each noun has its declension presented to the reader as a
guide to how it might generally look in dialects other than Standard
Eittlandic, however variations may exist from one dialect to another.
For instance, while most Eittlandic dialects lost the /ru/ part of the
dat.pl. declention, going from /férum/ to /fém/, some dialects in East
Northern Eittland still retain the former form.

Letters in parenthesis are no longer used when writing Eittlandic but
are still underlying vowels that can still affect the pronunciation of
the word and its surroundings. For instance, /dag/ can represent two
forms of the word /dag(r)/, /dag/ and /dag(a)/. The former is pronounced
{{{phon(daɣ)}}} while the latter is pronounced {{{phon(daj)}}}. They can also
represent grammatical cases which are no longer used in Standard
Eittlandic, such as /dag(r)/ shown above which doesn’t exist as /dagr/ in
Standard Eittlandic, only as /dag/. The underlying vowel also reappears
when the word is used in its definite form. For instance, /dagr/ becomes
/dagann/ due to the underlying «a» in its accusative form /dag(a)/ while
/fiskr/ becomes /fiskinn/ (the «i» is added when no other vowel can
replace it). To symbolize which definite article is used with nouns,
it is indicated between parenthesis in the accusative case, preceeded
by a dash, as in /dag(a-n)/.

** A

** Á

** Æ

** B
*** bræðr
sm. {{{phon(brɛð)}}}

See [[file:dictionary.md#broð][/bróð/]]

*** bróð
sm. {{{phon(brɔ̀ð)}}} , from ON [[https://old-norse.net/html/b.php#br%C3%B3%C3%B0ir][bróðir]]

1. brother, plural /bræð/

Re-analysis of ON /bródir/ decomposed into /bróð/ + /-ir/ by popular
etymology. Same goes for its former plural /bræðir/ which got
re-analyzed into /bræð/ + /-ir/.

| / |  <r> |          |        |
|   |      | Singular | Plural |
|---+------+----------+--------|
|   | Nom. | bróðr    | bræðr  |
|   | Acc. | bróð     | bræð   |
|   | Gen. | bróðir   | bræðir |
|   | Dat. | bróð     | bræðum |

*** bók
sf. {{{phon(bɔ̀k)}}}, from ON [[https://old-norse.net/html/b.php#b%C3%B3k2][bók]]

1. book, plural /bøk/

| / |  <r> |          |        |
|   |      | Singular | Plural |
|---+------+----------+--------|
|   | Nom. | bókr     | bøkr   |
|   | Acc. | bók      | bøk    |
|   | Gen. | bókar    | bøkar  |
|   | Dat. | bók      | bøkum  |

*** bøk
sf. {{{phon(bø̀k)}}}

See [[file:dictionary.md#bok(r)][/bók/]]

** C

** D
*** djúp
adj. {{{phon(dʒòp)}}}, from ON [[https://old-norse.net/html/d.php#dj%C3%BApr][djúpr]]

1. deep
2. profound (figuratively)

*** djúplig / djúpleg
adv. {{{phon(dʒòpleɣ)}}}, from OE djúpr (see [[file:dictionary.md#djúp][djúp]]) with OE suffix /-ligr/ (see
ON [[https://en.wiktionary.org/wiki/-ligr#Old_Norse][-ligr]])

1. deeply
2. inherently

*** dótt
sf. {{{phon(dɔtʃ)}}}, from ON [[https://old-norse.net/html/d.php#d%C3%B3ttir][dóttir]]

1. daughter

| / |  <r> |          |        |
|   |      | Singular | Plural |
|---+------+----------+--------|
|   | Nom. | dóttr    | dœttr  |
|   | Acc. | dótt     | dœtt   |
|   | Gen. | dóttr    | dœtr   |
|   | Dat. | dótt     | dœttum |

** Đ

** E
*** edd(a-t)
wf. {{{phon(e:d)}}}, from ON [[https://old-norse.net/html/e.php#edda][edda]]

1. great grandmother
2. female ancestor, beyond the grandmother

| / |  <r> |          |        |
|   |      | Singular | Plural |
|---+------+----------+--------|
|   | Nom. | edd      | eddr   |
|   | Acc. | edd      | edd    |
|   | Gen. | eddas    | eddas  |
|   | Dat. | edd      | eddam  |

*** Eittland
wn. {{{phon(ɑɪʔlɑnd)}}}, from OE neutral /einn/ (/alone/, /lonely/), itself from
ON [[https://old-norse.net/html/e.php#einn][einn]], and ON [[https://old-norse.net/html/l.php#land][land]]

1. High Kingdom of Eittland
2. island of Eittland

| / |  <r> |           |
|   |      | Singular  |
|---+------+-----------|
|   | Nom. | eittland  |
|   | Acc. | eittland  |
|   | Gen. | eittlands |
|   | Dat. | eittland  |

** É

** F
*** fað
m. {{{phon(fað)}}}, from ON [[https://old-norse.net/html/f.php#fa%C3%B0ir][faðir]]

1. father, plural /feð/

Re-analysis of sg. /fadir/ and pl. /feðir/ as /fað/ and /feð/ respectively,
each appended with a grammatical /-r/ or /-ir/ (which later got reduced to
/-r/).

|      | Singular | Plural |
|------+----------+--------|
| Nom. | faðr     | feðr   |
| Acc. | fað      | feð    |
| Gen. | faðar    | feðar  |
| Dat. | fað      | feðum  |

*** feð
sm. {{{phon(feð)}}}

See [[file:dictionary.md#fað][/fað/]]

*** fé
wn. {{{phon(fɛ̀)}}}, from ON [[https://old-norse.net/html/f.php#f%C3%A9][fé]] (cattle)

1. wealth

|      | Singular | Plural |
|------+----------+--------|
| Nom. | fé       | fé     |
| Acc. | fé       | fé     |
| Gen. | fés      | fés    |
| Dat. | fé       | fém    |

*** fisk
sm. {{{phon(fiʃk)}}}, from ON [[https://old-norse.net/html/f.php#fiskr][fiskr]]

1. fish

|      | Singular | Plural |
|------+----------+--------|
| Nom. | fiskr    | fiskr  |
| Acc. | fisk     | fisk   |
| Gen. | fiskar   | fiskar |
| Dat. | fisk     | fiskum |

** G
*** gauð
n. {{{phon(jɔʊð)}}}, from ON [[https://old-norse.net/html/g.php#gau%C3%B0][gauð]] (/a barking/)

1. a quarrel
2. a heated debate /(informal)/

*** gegn
adv. {{{phon(jeɡn̩)}}}

1. against, opposing
*** gjøf
f. {{{phon(jøv)}}}

1. gift, present

** H
*** heils(a-t)
wn.f. {{{phon(hɑ:ɪls)}}}

1. health

*** hjól
n. {{{phon(çɔl)}}}

1. wheel

*** hlóð
n. {{{phon(l̥ɔð)}}}

1. hearth
2. living room

*** hneis(a-t)
wn.f. {{{phon(n̥ɑ:ɪs)}}}

1. shame, disgrace
2. social isolation

*** hneising
n. {{{phon(n̥ɑɪsinɡ)}}}

1. hermit
2. (modern) shut-in, hikikomori

*** hnjós(a)
v. {{{phon(ɲ̥ɔ̀ːs)}}}

1. to sneeze

*** hrifs
n. {{{phon(r̥ivs)}}}

1. assault, mugging
*** hvat
adv. {{{phon(ʍɑt)}}}

1. what
*** hví
adv. {{{phon(ʍè)}}}

1. why

** I

** Í

** J

** K
*** kaup
n. {{{phon(kɔp)}}}

1. commerce
2. bargain, barter

*** konung
sn.m. {{{phon(ˈkonoŋ)}}}

1. king

*** konunɡliɡ
{{{phon(konoŋleɣ)}}}, from [[file:./dictionary.md#konung][konung]] and suffix /-lig/.

1. adv. royaly
2. adj. royal

** L

** M
*** myrɡun
m. {{{phon(ˈmyrɡun)}}}

1. morning, aurora

*** metr(o)
wn.n. {{{phon(metr)}}}, from French “métro”

1. subway, underground

- definitive form: /metrot/

See also [[file:./dictionary.md#undirland][undirland]]

** N
*** ná
adv. {{{phon(nɛ̀)}}}

1. now
   #+html: ::: tip Example
   Ná kom ek frá universitatit.

   I come from the university now.
   #+html: :::
2. intensifier, used at the end of sentences
   #+html: ::: tip Example
   Ek kom frá universitatit ná!

   - I come from the university (you know)
   or
   - (I’ll have you know) I come from the university!
   #+html: :::
3. progressive marker when placed right after the verb
   #+html: ::: tip Example
   Ek kom ná frá universitatit.

   I’m coming from the university.
   #+html: :::

*** noregsúlf
m. {{{phon(ˈnorejsˌòlv)}}}

1. wolf, litt. Norway’s wolf.

   Wolves do not naturally live in Eittland. Their only relatives
   introduced to the island were dogs and wolf-dogs, and the latter
   inherited the simpler /úlfr/ term. Noun composed by Old Norse /noregs/
   (genitive of /Noregr/, /Norway/) and /úlfr/.

** O

** Ó
*** óglaðr / óglœðr
adj. {{{phon(ˈɔ̀ɡʲœðr̩)}}}

1. very sad, depressed, miserable

** Ø

** Œ
*** Œgir / Œger
m. {{{phon(ˈœjer)}}}

1. A mythical beast residing in the forests of the western
Eittlandic fjords.

** P
*** pengvin / pengven
n. {{{phon(ˈpeŋβen)}}}

1. penguin

From English *penguin*

** Q

** R
*** ráðuneyt
wn.m. {{{phon(ˈrɛ̀ðoˌnœʏt)}}}

1. Ministry
2. department

** S
*** sitj(a)
v. {{{phon(siːtʃ)}}}

1. to sit
2. to represent (politics)

*** sjá
v. {{{phon(ʃɛ̀)}}}

1. to see
2. to understand

*** skilj(a)
v. {{{phon(ʃkiːʎ)}}}

1. to differenciate
2. to segregate, to separate
3. to understand a difference

*** snjór
m. {{{phon(sɲɔ̀r)}}}

1. snow

*** styrsamhald
n. {{{phon(ˈʃtyrˌsamhald)}}}

1. military batallion
2. mitilary unit, group

From Old Norse *styrr* (stir, battle) and *samhald* (a holding together,
unity).

** T
*** tal(a)
wn.f. {{{phon(tal)}}}

1. numbers

*** tren
wn.n. {{{phon(tren)}}}

1. train

** Þ

** U

*** undir
adj. {{{phon(undir)}}}

1. under, underneath

Can only be used with accusative or dative

*** undirland
wn.n. {{{phon(ˈundirˌland)}}}, calque of English “underground”

1. underground, subway

See also [[file:./dictionary.md#metr-o][metr(o)]]

*** universitat
wn.n. {{{phon(oneˈβersetat)}}}

1. university

*** uppá
prep. {{{phon(ˈupɸə̀)}}}

1. upon

** Ú
*** úlf
m. {{{phon(òlv)}}}

1. wolf-dog. See also /noregsúlfr/.

** V
*** veisheit
wn.f. {{{phon(ˈβɑɪshɑɪt)}}}

1. knowledge or wisdom. From German /Weisheit/. See also /vizka/

*** vél
sc.f.

1. machine, craft

*** vétal
wn.f. {{{phon(ˈβɛ̀tal)}}}

1. computer

*** visk(a)
f. {{{phon(βiːʃk)}}}

1. practical knowledge or wisdom, acquired from experience
See /veisheit/ for a more general term for /wisdow/

** Y

** Ý

** Z
