name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - uses: purcell/setup-emacs@master
        with:
          version: 29.1
      - name: "Export org to md"
        run: emacs -Q --script export.el
      - run: npm run build
      - name: "Deploy to Cloudflare Pages"
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          projectName: conlang-phundrak-com
          directory: docs/.vuepress/dist/
          githubToken: ${{ secrets.TOKEN }}
